controllers:
    resource: ../src/Controller/
    type: attribute

# the "app_lucky_number" route name is not important yet
#app_lucky_number:
#    path: /my_project/public/lucky
#    controller: App\Controller\LuckyController::number
